using System.Runtime.InteropServices;

namespace ImageQT.Models.Linux.Display;

[StructLayout(LayoutKind.Sequential)]
public unsafe struct EventVec
{
    // repeat this 128 times
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector0; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector1; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector2; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector3; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector4; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector5; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector6; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector7; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector8; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector9; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector10; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector11; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector12; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector13; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector14; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector15; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector16; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector17; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector18; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector19; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector20; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector21; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector22; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector23; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector24; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector25; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector26; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector27; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector28; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector29; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector30; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector31; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector32; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector33; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector34; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector35; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector36; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector37; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector38; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector39; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector40; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector41; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector42; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector43; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector44; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector45; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector46; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector47; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector48; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector49; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector50; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector51; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector52; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector53; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector54; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector55; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector56; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector57; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector58; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector59; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector60; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector61; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector62; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector63; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector64; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector65; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector66; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector67; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector68; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector69; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector70; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector71; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector72; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector73; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector74; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector75; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector76; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector77; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector78; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector79; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector80; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector81; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector82; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector83; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector84; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector85; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector86; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector87; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector88; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector89; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector90; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector91; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector92; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector93; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector94; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector95; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector96; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector97; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector98; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector99; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector100; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector101; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector102; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector103; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector104; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector105; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector106; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector107; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector108; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector109; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector110; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector111; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector112; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector113; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector114; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector115; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector116; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector117; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector118; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector119; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector120; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector121; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector122; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector123; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector124; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector125; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector126; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> EventVector127; // dpy, re, event
}