using System.Runtime.InteropServices;

namespace ImageQT.Models.Linux.Display;

[StructLayout(LayoutKind.Sequential)]
public unsafe struct WireVec
{
    // repeat this 128 times
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector0; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector1; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector2; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector3; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector4; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector5; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector6; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector7; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector8; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector9; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector10; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector11; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector12; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector13; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector14; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector15; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector16; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector17; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector18; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector19; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector20; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector21; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector22; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector23; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector24; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector25; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector26; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector27; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector28; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector29; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector30; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector31; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector32; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector33; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector34; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector35; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector36; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector37; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector38; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector39; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector40; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector41; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector42; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector43; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector44; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector45; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector46; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector47; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector48; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector49; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector50; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector51; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector52; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector53; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector54; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector55; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector56; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector57; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector58; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector59; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector60; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector61; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector62; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector63; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector64; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector65; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector66; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector67; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector68; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector69; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector70; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector71; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector72; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector73; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector74; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector75; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector76; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector77; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector78; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector79; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector80; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector81; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector82; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector83; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector84; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector85; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector86; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector87; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector88; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector89; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector90; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector91; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector92; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector93; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector94; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector95; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector96; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector97; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector98; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector99; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector100; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector101; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector102; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector103; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector104; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector105; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector106; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector107; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector108; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector109; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector110; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector111; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector112; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector113; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector114; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector115; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector116; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector117; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector118; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector119; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector120; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector121; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector122; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector123; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector124; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector125; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector126; // dpy, re, event
    public delegate* unmanaged[Cdecl]<nint, nint, nint, int> WireVector127; // dpy, re, event
}